#!/bin/python3
# PYTHON_ARGCOMPLETE_OK

from parsecmdline import parsecmdline

parsecmdline()

from parselambda import parseLambdaGroupTypes
import utility

parseLambdaGroupTypes()

utility.inspect()
